# REPORT 
## INTRODUCTION

The aim of this study is to analyze United States wildlife and wildlife product imports. For this purpose, we'll review 15 years (2000-2014) of data from the Law Enforcement Managment Information System (LEMIS), originally collected by the United States Fish and Wildlife Service (USFWS), cleaned, standardized and stored into a R package called lemis by EcoHealth Alliance. You can find more information more about this dataset [Here](https://www.nature.com/articles/s41597-020-0354-5).

## METHOD AND DATA INCLUDED
The data collected by EcoHealth Alliance includes records of plants, microorganisms and animals, among others. For this analysis, we'll exclude those elements belonging to fungi, plantae, bacteria, chromista and unspecified kingdoms, considering only those organisms of the Kingdom Animalia. 

Between January 01, 2000, and December 31, 2014, around **2 millions wildlife shipments were imported into the United States**, involving around 11,5 billions of wildlife items plus 1,1 billion kg of wildlife items only measured in weight.  

A **shipment** refers to any container or group of containers that share a common control number, country of shipment and shipment date. Each shipment may be represented in the lemis dataset by multiple segments or rows, because the contents are derived from more than one species or type of product. 

We will analyze the data based on different topics and trends. We'll analyze the number of seized shipments, as well as their volume and content.  

## KEY FINDINGS




## RESULTS BY TOPIC

### Shipments
There are 2,079,637 unique shipments containing 5,451,832 segments.

- Of those, 60% (1,265,491 unique shipments) represent single segments. It means that for 1,265,491 shipments only one species and one type of product were discovered. The remaining 40% (814,146 unique shipments) contain 4,186,341 segments.

- These multiple segments shipments contain from 2 to 492 segments. The average number of segments in this kind of shipments is 5; the median is 3. 


### Description
**Based on the types of items by segment**, most of them contain "Live specimens" (29%), followed by trophies (17%), "shell products" (9%), small leather products (7%) and jewelry (6%)

<iframe src="./plotly/description.html" width="100%" height="400" id="igraph" scrolling="no" seamless="seamless" frameBorder="0"> </iframe>

- Most of the "live specimens" are corals (38%) and fishes (23%)
- Most of the "trophies" are from mammals (89%)
- Most of the "shell products" are from shells (98%)
- Most of the "small leather products" are from reptiles (81%) 
- Most of the "jewelry" is from shells (93%)

<iframe src="./plotly/descriptions_taxa.html" width="100%" height="400" id="igraph" scrolling="no" seamless="seamless" frameBorder="0"> </iframe>

**Based on the number of items**, jewelry, shells, feathers, hair products and eggs (dead or blown) are the most common products.

**Based on the kg of items**, meat, dead animals, frog legs, live specimens and shells are the most common products.

### Purpose 
**Based on the purpose of items by segment**, most of the segments contain "Commercial" (75%) and "hunting trophies" (18%). 

<iframe src="./plotly/purposes.html" width="100%" height="600" id="igraph" scrolling="no" seamless="seamless" frameBorder="0"> </iframe>

- Most of the segments were imported for commercial purposes. Most of their items came from shells (27%), corals (17%) and reptils (17%).

- Hunting trophies imports made up 18% of all segments. They mainly involved mammals (87%) and birds (13%)

- Personal imports made up 3% of all segments. They involved mammals (49%), birds (14%) and reptiles (13%)

<iframe src="./plotly/purpose_taxa.html" width="100%" height="600" id="igraph" scrolling="no" seamless="seamless" frameBorder="0"> </iframe>

### Source
**Based on the source of the items by segment**, the most common sources in the segments are "specimens taken from the wild" (78%) and "animals bred in captivity" (15%).

<iframe src="./plotly/sources.html" width="100%" height="600" id="igraph" scrolling="no" seamless="seamless" frameBorder="0"> </iframe>

### Ports, countries and trade routes
**This involves the ports of entry, the country of export and the country of origin.**

**Shipments comes from 252 different countries of origin, although 75% of all the imports comes from the same 15 countries.** The top-five countries of origin were Indonesia (15%), Canada (10%), South Africa (9%), Philippines (8%) and China (7%).

<iframe src="./plotly/county_origin.html" width="100%" height="400" id="igraph" scrolling="no" seamless="seamless" frameBorder="0"> </iframe>

**Shipments were exported to the UUEE from 257 different countries, although 75% of all the imports were exported from the same 15 countries.**
The top-five countries of export were Canada (12%), Indonesia (12%), South Africa (8%), Philippines (8%) and Italy (7%)

<iframe src="./plotly/country_exp.html" width="100%" height="400" id="igraph" scrolling="no" seamless="seamless" frameBorder="0"> </iframe>

Although [there are around 328 ports of entry into the EEUU](https://www.cbp.gov/), only 73 of them are represented in this dataset. This is because not all of them are covered by FWS wildlife inspectors. By law, [only 18 of them are designated ports with  full-time inspectors](https://www.fws.gov/le/wildlife-inspectors.html).

Based on the number of imports, the top-five ports of entry were Los Angeles (20%), New York(19%), Miami(6%), Newark(5%) and San Francisco(5%). 

<iframe src="./plotly/port_of_entry.html" width="100%" height="400" id="igraph" scrolling="no" seamless="seamless" frameBorder="0"> </iframe>

The top-five most used trade routes (country of export to port of entry) emerged from this analysis were: 
Indonesia to Los Angeles, CA (7%), Italy to New York, NY (4%), South Africa to New York, NY (2%), Hong Kong SAR China to New York, NY (2%) and Philippines to Los Angeles, CA (2%). 


### Refused segments
98.28% of imports were legally declared, just 1.73% was refused. Most of the refused shipments included items related with mammals (28%) and reptils (27%).

The top-five countries of origin were: Unknown (24%), Mexico (14%), Canada (7%), Indonesia (6%) and China (6%).

The top-five countries of export were: Mexico (19%), Canada (10%), China (8%), Indonesia (5%) and Philippines (4%)

The top-five ports were: New York, NY (9%), El Paso, TX (8%), Anchorage, AK (8%), Los Angeles, CA (8%), San Francisco, CA (6%). 


## RESULTS BY TRENDS 
The trends analysis will focus on the number of seized shipments, the import (US dollars), the contents and the capacity of deter ilegal shipments (refused shipments). 

### Seized wildlife shipments and segments
**In the 15 years analyzed, there are 2,079,637 unique shipments containing 5,451,832 segments.** We can see a clear upward trend in the number of cases from 2000 to 2006. Then, the curve reached its peak with around 162,000 unique shipments, decreased a bit, and started leveling off. 

<iframe src="./plotly/unique_seized_shipments_per_year.html" width="100%" height="400" id="igraph" scrolling="no" seamless="seamless" frameBorder="0"> </iframe>

### Import (US dollars)
- **There has been an upward trend in the amount of dollars spent** from 2000 to 2012 (Although we don't have enough information about this variable in the data produced between 2008-2011 and 2013-2014. For more information, check the section 2.1.1.).

<iframe src="./plotly/dollars_shipyear.html" width="100%" height="400" id="igraph" scrolling="no" seamless="seamless" frameBorder="0"> </iframe>

**Items that involved mammals, shells and reptiles generate the highest amount of money throughout the years**

<iframe src="./plotly/dollars_year_taxa.html" width="100%" height="400" id="igraph" scrolling="no" seamless="seamless" frameBorder="0"> </iframe>

### Content/quantity

### Refused segments
As we mentioned before, 98.28% of imports were legally declared, just 1.73% was refused. 



### Pending info
- **54% of dispositions took place within a month of the shipment date (most of them within a week)**








