--- 
title: "Faunalytics - Wildlife trade dataset"
date: "`r Sys.Date()`"
description: ''
documentclass: book
link-citations: yes
site: bookdown::bookdown_site
biblio-style: apalike
---

# Introduction
The aim of this study is to analyze United States wildlife and wildlife product imports. For this purpose, we'll review 15 years (2000-2014) of data from the Law Enforcement Managment Information System (LEMIS), originally collected by the United States Fish and Wildlife Service (USFWS), cleaned and stored into a R package called lemis by EcoHealth Alliance. You can find more information more about this dataset [Here](https://www.nature.com/articles/s41597-020-0354-5)

The data collected by EcoHealth Alliance include includes records of plants, microorganisms and animals, among others. For this analysis, we'll exclude those elements belonging to fungi, plantae, bacteria, chromista and unspecified kingdoms, considering only those organisms of the Kingdom Animalia. 

Between January 01, 2000, and December 31, 2014, around **2 millions wildlife shipments were imported into the United States**, involving around 11,4 billions and 1,1 billion kg of wildlife items. 

A **shipment** refers to any container or group of containers that share a common control number, country of shipment and shipment date. Each shipment may be represented in the lemis dataset by multiple segments or rows, because the contents are derived from more than one species or type of product. 

We will analyze the data based on different topics and trends. We'll analyze the number of shipments, as well as their volume and content.  

